Django_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('comments.urls')),
    path('all/rss/',AllPostsRssFeed(),name='rss'),
]

blog/urls.py
from django.urls import path

from . import views

#添加命名空间，为多应用做预留，防止多应用中的URL混淆
app_name='blog'

urlpatterns=[
    #主页
    path('',views.IndexView.as_view(),name='index'),
    path('post/',views.IndexView.as_view(),name='index2'),
    #文章详情页
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='detail'),
    #归档页
    path('archives/<int:year>/<int:month>',views.ArchivesView.as_view(),name='archives'),
    #分类页
    path('category/<int:pk>',views.CategoryView.as_view(),name='category'),
    #标签页
    path('tag/<int:pk>',views.TagView.as_view(),name='tag'),
    #关于我
    path('about/',views.about,name='about'),
    #联系
    path('contact/', views.contact, name='contact'),


]

comments/urls.py
from django.urls import path

from . import views
app_name='comments'
urlpatterns = [
    path('comment/post/<int:post_pk>',views.post_comment,name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags
import markdown

# Create your models here.

#分类表

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

#标签表
class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

#文章表
class Post(models.Model):
    #文章标题
    title = models.CharField(max_length=100)
    # 文章摘要
    abstract = models.CharField(max_length=200, blank=True)
    #文章正文
    body = models.TextField()
    #文章作者,是多对一的关系，使用django给我们设计好的表
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    #文章创建时间
    created_time = models.DateTimeField()
    #文章最新修改时间
    modified_time = models.DateTimeField()
    # 文章阅读量
    views = models.PositiveIntegerField(default=0)
    #外键关系：文章与分类是多对一的关系、所以在多的一端设置外键。
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    #外键关系: 文章与标签是多对多的关系，一篇文章可以有多个标签，一个标签下可以有多篇文章。可以为空。多对多的关系定义在哪张表都可以
    #但是一般定义在需要编辑表单的地方，我们这里肯定是博客添加标签，而不是标签添加博客。
    tags = models.ManyToManyField(Tag,blank=True)

    def __str__(self):
        return self.title

    #添加文章阅读量的函数
    def increase_views(self):
        self.views += 1
        self.save()

    #重写模型的保存函数
    def save(self,*args,**kwargs):
        #如果没有写摘要
        if not self.abstract:
            #渲染文章正文的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
            ])
            #去掉HTML标签，而取前50个摘要
            body=self.body
            self.abstract = strip_tags(md.convert(body))[:50]
        super(Post,self).save(*args,*kwargs)

    class Meta:
        ordering = ['-created_time']

comments/models.py
from django.db import models

# Create your models here.


#Comment表
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    #外键，多对一的关系,删除时级联
    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']

blog/views.py
from django.shortcuts import render, get_object_or_404
import markdown
# Create your views here.
from django.http import HttpResponse
from .models import Post,Category,Tag
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension


#自定义获取全部列表通用视图类
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    #分页，每页10篇文章
    paginate_by = 10

#自定义获取分类列表的视图类，继承IndexView类
class CategoryView(IndexView):
    #重写获取的方法
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)

#自定义获取归档的视图类，依旧继承IndexView类
class ArchivesView(IndexView):
    #重写获取的方法
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        #这里注意mysql时区的设置
        return super(ArchivesView,self).get_queryset().filter(created_time__year=year,created_time__month=month)


#自定义标签的视图类
class TagView(IndexView):

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tags=tag)

#自定义获取详情的通用视图类
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    #重写get方法
    def get(self, request, *args, **kwargs):
        #先调用get方法，才会返回self.object属性
        response = super(PostDetailView,self).get(request,*args,**kwargs)
        #文章阅读量增加
        self.object.increase_views()
        return response

    #重写该方法，对post的body转化成HTML
    def get_object(self, queryset=None):
        post = super(PostDetailView,self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      TocExtension(slugify=slugify),
                                     ])


        post.conv_body = md.convert(post.body)
        post.toc = md.toc
        return post

    #重写get_context_data函数,添加评论的数据给模版文件
    def get_context_data(self, **kwargs):
        #这一步只获取到了post数据，详情页面还有评论的数据
        context = super(PostDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context



#关于我页面
def about(request):
    return render(request,'blog/about.html')

#联系页面
def contact(request):
    return render(request,'blog/contact.html')




#
# # 返回渲染的博客主页
# def index(request):
#     # 从数据库中查询所有文章并按时间排序
#     post_list = Post.objects.all()
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#
#
# # 返回渲染的文章详情主页
# def detail(request, pk):
#     # 查询是否有该文章
#     post = get_object_or_404(Post, pk=pk)
#     #增加阅读量
#     post.increase_views()
#     post.body = markdown.markdown(post.body,
#                                   extensions=[
#                                       'markdown.extensions.extra',
#                                       'markdown.extensions.codehilite',
#                                       'markdown.extensions.toc',
#                                   ]
#                                   )
#     form =CommentForm()
#     comment_list = post.comment_set.all()
#     context = {
#         'post':post,
#         'form':form,
#         'comment_list':comment_list,
#     }
#
#     return render(request, 'blog/detail.html', context=context)
#
# #时间归档视图函数
# def archives(request,year,month):
#     #这里遇大坑，MYsql数据库时区的问题，google了才解决
#     post_list = Post.objects.filter(created_time__year=year,created_time__month=month)
#     return render(request,'blog/index.html',context={'post_list': post_list})
#
# #分类页面
# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request,'blog/index.html',context={'post_list': post_list})

comments/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from blog.models import Post
from django.urls import reverse

from .models import Comment
from .forms import CommentForm
# Create your views here.

def post_comment(request,post_pk):
    post = get_object_or_404(Post,pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('blog:detail',args=(post.pk,)))
        else:
            #数据不合法
            comment_list = post.comment_set.all()
            context = {
                'post':post,
                'form':form,
                'comment_list':comment_list,
            }
            return render(request,'blog/detail.html',context=context)
    return HttpResponseRedirect(reverse('blog:detail',args=(post.pk,)))

blog/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>JackyLove's个人博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!-- link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"-->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/autumn.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>JackyLove的个人博客网站</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
{#<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>#}
{#<div class="copyrights">Modified by <a href="https://www.jackylove.me/">JackyLove的博客</a></div>#}

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
            {% block main %}
            {% endblock main %}
            </main>
            {% block toc %}
            {% endblock toc %}
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章!
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                                <span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类!
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂时无标签!
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>

            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 前端模版下载自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模版之家</a>
                    - 由<a href="https://www.jackylove.me" title="JackyLove's个人博客" target="_blank">JackyLove</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

blog/templates/blog/about.html
{% extends 'base.html' %}
{% block main %}

一个爱唱歌的码农，不想运动。<br>

爱文学的理科生，喜欢动漫。<br>

想谈一场不分手的恋爱，🥚至今还是🐶。<br>

被迫读研，想去打工赚💰(so poor)。<br>

嗯，就酱。<br>

哦，对了，还有喜欢玩游戏，实不相瞒，国服第一亚索正是在下(认真脸）。<br>
{% endblock %}

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% block main %}
    联系方式:<br>
    Email:xxx@xxx.com<br>
    QQ:10086<br>
    Github:<a href="https://github.com/jacklov3/">Github</a>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
    <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.conv_body|safe }}
                    </div>
                </article>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">所属标签</h3>
                    <ul>
                    {% for tag in post.tags.all %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                    {% empty %}
                        没有所属标签!
                    {% endfor %}
                    </ul>

                </div>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">URL：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
 <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
{% endblock toc %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.abstract }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'blog:detail' post.pk %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-posy">暂时还没有发布的文章！</div>
                {% endfor %}

                {% if is_paginated %}
                <div class="pagination-simple">
                    {% if page_obj.has_previous%}
                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                {% endif %}
{% endblock main %}